### ISSUE TITLE
Add vendor to namespace

### ISSUE THREAD

**Issue by cjhaas** [kekse1/count.php#1]
Right now the code lives in the global `counter` namespace. The general pattern that most code/libraries follows is to have the vendor (company, developer, etc.) be the root namespace, and the package to be the sub-namespace. This is not a requirement, but it is ubiquitous enough to be a defacto standard. I would recommend changing the namespace to `kekse1\counter` or similar. As a developer, this helps me know/remember where the heck I got `counter` or `count.php` in the first place without diving deep into the code.

**Comment by kekse1** [comment]
Aaah.. got it now!
So I've changed it to `kekse\counter`.

**Comment by kekse1** [comment]
ok, question: atm it's `kekse\counter\counter()`..

Wouldn't it be more appropiate to use `namespace kekse`, so the base function would be `kekse\counter()`?

**Comment by cjhaas** [comment]
I don’t think there’s a right or wrong for sub-namespaces. Monolog, which is installed in a ton of places uses [just a single namespace](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php). I think the vendor\package is more common, however. Do you ever plan on releasing another PHP package?

**Comment by kekse1** [comment]
Ok, so now it's `namespace kekse`, as the sub `counter` is defined under it. More pretty this way..

Heh.. no I don't have any plans. But nevertheless your
tip w/ vendor namespace was very helpful. Thank you.

**Comment by kekse1** [comment]
https://github.com/kekse1/count.php#namespace
-> As you teached me! ^_^

**Comment by kekse1** [comment]
OMG. No way.. I'm going to use a `class` nevertheless. TODO!
