### ISSUE TITLE
unexpected token "readonly"

### ISSUE THREAD

**Issue by cjhaas** [kekse1/count.php#2]
After downloading this I tried to run `php count.php`, `php count.php --test` and `php count.php --help`, and they all resulted in:

```
PHP Parse error:  syntax error, unexpected token "readonly" in /mnt/f/dev/count.php/php/count.php on line 4263
```

Which is this: https://github.com/kekse1/count.php/blob/8304a023756fc642da1d81dda0da3429d8d8b6d8/php/count.php#L4263

**Comment by kekse1** [comment]
OMG. As if `READONLY` would be a PHP internal or so!?
So I renamed it to `RO` and it worx! xD~
